---
title: "Spew To-do List"
output: html_document
author: "Sam, Shannon, and Lee"
---

## Implement IPUMS functions 
- Save an example data-set into the spew `data/` folder  
- read.R
- format.R

## Schools/Workplaces
- Need to add in the schools + workplaces modules for the United States data 

## Canadian PUMS
- Use this as a text case for generating a "custom" synthetic population. 
  
  IE: By specifying the filepaths, Location ID's, etc... This will give us a text case to make sure that someone who has these three data-sources but aren't in our format can still use the program. 
  
  In fact, we should probably re-write the "read.R" functions so that the only data_group = "US" part that matters is specifying **where** the locations are. The functions for actual reading, then, should be agnostic to the filenames. Although I'm sure practical issues will overwhelm this ideal  

## Improve make.R
- Add in checks which verifies the two PUMS have the same serial numbers (currently assuming this is true)
- Also check to make sure that the puma_ids (if used) match. 
- For now, if there are multiple polygons to sample, I am just sampling from 
the first one for convinience. In the future, we may want to think of something 
more elegant here (such as a union)

## Improve read.R
- Update read.R so that it can now read and standardize miscellaneous data sources. For me, the three groups should be "US", "ipums", and "none". Where in "none", you can specify the filepaths for each one of the data sources. More inpute will be needed to the "none" group, however, since we will need to know which row is the place_id, puma_id, etc...

## Improve spew.R function  
- Add in a variable which specifies the variables to generate
- Add an input which specifies the ID variable used for linking the individual 
and household PUMS (maybe add this to spew.R?)

## Unit tests
- read.R (finish testing individual functions, test the entire function as well)
- format.R 
- make.R

## Document each new function
- Read functions 
- Format Functions 

## Implement IPUMS format.R functions extensions
- Note that the core of format.R should work with the ipums files, 
  it's simple for the USA since we only need to add a column to the poptable. 

## Add in a diagnostics function
- Go into a synthetic population directory and create 
summary statistics and plots which display the output in an
easily human interpretable manner. Used as a sanity check 

## Add in a clickable feature to donwload the synthetic ecosystems 
- Shiny "Map" is a refinement
- Needs to be clickable!

## Add in a feature which can include mosquitoes
- Use the vector map data!!!

## Write up Version Control for guidelines 
- Use Hadley's git/github tutorial 

## Code reviews
- Read more about (Guo's Article) http://pgbovine.net/CACM-group-code-reviews.html 