#' Create plot of synthetic households

#' Output our final synthetic populations as csv's 
#' 
#' @param df dataframe with the final synthetic population 
#' @param place_id numeric indicating the name of the particular region samples
#' @param type character vector with the type, either "household" or "people"
#' @param output_dir character containing the directory in which we want to 
#' write the final csv's 
#' @return data indicating the indices of people to sample 
write_data <- function(df, place_id, type, output_dir) {
  filename <- paste0(output_dir, type, "_", as.character(place_id), ".csv")
  write.table(df, filename, sep = ",", row.names = FALSE, qmethod = "double")
}


#' Plot the synthetic household populations on a map
#' @param region_name character name of the region for use in finding with ggmap
#' @param hh_pop the synthetic population generated by spew for a given region
#' @param region_shape shapefile of the region ONLY
#' @param z zoom for ggmap 10 is far in, 1 is far out
#' @param title_map - title for the map
#' @return plot of the region, a ggmap object

plot_pop <- function(region_name, hh_pop, region_shape, zoom=8, title_map=region_name){
    #fortify the shape for ggplot
    shape.fort <- fortify(region_shape)
    # get the centers for labeling
    center.df <- as.data.frame(coordinates(region_shape))
    names(center.df) <- c("Longitude", "Latitude")
    center.df$region <- region_name
    print(center.df)
    #get hte map
    google.map <- get_map(region_name, zoom=zoom, maptype="roadmap")
    df.coords <- subset(hh_pop, select=c("latitude","longitude"))
    #making the actual map
g <- ggmap(google.map) +
    geom_polygon(aes(x = long, y = lat, group = group), data=shape.fort,
                 colour = "darkgreen", fill = NA, alpha = .4, size = 2, cex=3) +
    geom_point(aes(x=longitude, y=latitude), data=df.coords, color="blue", size=.5) +
    geom_text(aes(label = region, x = Longitude, y = Latitude), data=center.df, 
              cex=5, font=2) +
    theme_nothing(legend=TRUE) +
	  ggtitle(title.map)
    print(g)
    return(g)
}
